spring:
  application:
    name: user-service # 服务名称
  profiles:
    active: test
  cloud:
    nacos:
      server-addr: 192.168.100.13 # nacos地址
      #      server-addr: 192.168.146.135 # nacos地址
      config:
        file-extension: yaml # 文件后缀名
        shared-configs: # 共享配置
          - dataId: shared-jdbc.yaml # 共享mybatis配置
          - dataId: shared-log.yaml # 共享日志配置
          - dataId: shared-redis.yaml # 共享redis配置
          - dataId: shared-mq.yaml # 共享mq配置